### ISSUE TITLE
Suggest "brew doctor"

### ISSUE THREAD

**Issue by jcburley** [danielfrance/Installing-Ruby-On-M1-Macs#2]
Immediately after installing Homebrew (from scratch, which should be stressed as important to do, especially if problems are encontered), I found that running `brew doctor` and getting rid of stuff it warned about — in my case, it was very likely old entries in `/usr/local/lib/` — could unblock users.

Doing that _before_ `brew install rbenv` and such would seem wise.

**Comment by danielfrance** [comment]
done. thanks for the suggestion
